spring:
  cloud:
    azure:
      servicebus:
        connection-string: <service-bus-connection-string>
    stream:
      bindings:
        consume-in-0:
          destination: events
      servicebus:
        queue:
          bindings:
            consume-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume;
      poller:
        fixed-delay: 1000
        initial-delay: 0
server:
  port: 8090
